### ISSUE TITLE
feature request: toggle clock on full-screen article view

### ISSUE THREAD

**Issue by Spleeeno** [yanus171/Flym#99]
hey there,

would it be possible to include a toggle for the clock display in the lower left corner with fullscreen articles?

edit: split up the requests

**Comment by yanus171** [comment]
Please separate it into two issues, so we can discuss (and close when finished) them separately

**Comment by Spleeeno** [comment]
done - reworded and split into 2 issues.

**Comment by yanus171** [comment]
What do you mean by TOGGLE? Just item in settings to turn it off?

**Comment by Spleeeno** [comment]
yeah, just a switch to turn it on or off

**Comment by yanus171** [comment]
And what about read progress bar near it. Does it also require turn off setting?

**Comment by ThomasLeigh** [comment]
**### Oh My**, I'd also to be able to customize those elements a little bit - I mean **their size and colors**. I dreeeeeaaaaam about ittttt :) !!!! Really, kidding aside, **the progress bar while reading is ### a great feature** - a great one which I greatly regret not to use because it's too small for My vision :( .

Shall I create a separate issue for that?

**Comment by yanus171** [comment]
Yes, please remove this to separate issue

**Comment by ThomasLeigh** [comment]
I think we could close this one.
